### ISSUE TITLE
Upgrade cmake on all buildbots

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-buildbot#54]
Once 0.5.0 is out the door, upgrade cmake on all the buildbots to [at least 3.4.3](http://llvm.org/releases/3.9.0/docs/ReleaseNotes.html).  [This script](https://github.com/staticfloat/julia-ansible-scripts/blob/master/cmake_install.yml), newly updated, should work just fine.

Note; do NOT upgrade mingw cross-compilers to 5.4,  we need to keep those held back to 4.9 until we have a solution for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77333

**Comment by tkelman** [comment]
Can we upgrade cmake just on power for now, so https://github.com/JuliaLang/julia/pull/18557 can be merged? Since the power buildbot is so new it's not a huge deal if the power build of an upcoming release gets delayed a tiny bit.

**Comment by staticfloat** [comment]
Should be done.  Feel free to try it out.

**Comment by tkelman** [comment]
I don't think it's on the path yet? https://build.julialang.org/builders/package_tarballppc64le/builds/88/steps/make/logs/stdio

**Comment by staticfloat** [comment]
Needed to shuffle around the PATH priorities in `.bash_profile`.  Restarted as https://build.julialang.org/builders/package_tarballppc64le/builds/89

**Comment by tkelman** [comment]
did that also result in a different compiler getting used? missing glibcxx version symbols?

**Comment by staticfloat** [comment]
Yes it did!  Apparently we weren't using the GCC 6.2 that I custom built on there before now.  I'll just nuke and restart.

**Comment by staticfloat** [comment]
New build: https://build.julialang.org/builders/package_tarballppc64le/builds/92

**Comment by tkelman** [comment]
oh you had done a gcc build there? didn't realize. this is a system we share with people right? so not feasible to run on some older centos 6 (if that works on power)? do we have permissions to run in a vm? might be a little slower but it's already our fastest buildbot

**Comment by staticfloat** [comment]
I don't think we have any virtualization software installed.  Would Docker be enough?

**Comment by tkelman** [comment]
yes, if that works on power. then we'd need to port your ansible scripts to dockerfiles which I'd kind of prefer myself, at least for linux

**Comment by tkelman** [comment]
or install ansible in the docker image I suppose

**Comment by staticfloat** [comment]
The ansible scripts have the advantage of being the same across all platforms, I'd kind of like to not split the configuration.

**Comment by tkelman** [comment]
Looks like it's missing one of the environment variables or make flags that we had to be careful about, to point at the right libstdc++ from the built gcc?

**Comment by staticfloat** [comment]
Fixed via
```
PATH=$HOME/local/bin:$HOME/bin:$PATH
LD_LIBRARY_PATH=$HOME/local/lib64:$HOME/local/lib:$LD_LIBRARY_PATH

export PATH
export LD_LIBRARY_PATH
```
In `~/.bash_profile`.  Silly me for forgetting.  New build going through [here](https://build.julialang.org/builders/package_tarballppc64le/builds/98).

**Comment by tkelman** [comment]
This will need doing on the centos 5 intel buildbots before we can merge https://github.com/JuliaLang/julia/issues/19123

**Comment by staticfloat** [comment]
Done, let's go ahead and test it.

**Comment by tkelman** [comment]
windows buildbots need this too, they're on the 3.3 cygwin package - be very careful if you upgrade this through cygwin setup though, need to manually switch to "keep" on all the mingw cross compilers to stay at 4.9

> Note; do NOT upgrade mingw cross-compilers to 5.4, we need to keep those held back to 4.9

**Comment by staticfloat** [comment]
> Note; do NOT upgrade mingw cross-compilers to 5.4, we need to keep those held back to 4.9

Thanks for reminding me of that, I do not remember writing that, and would have thought it was a good idea to upgrade everything.  :P  Windows buildslaves are updated as well now.

**Comment by tkelman** [comment]
I think something's broken about the cmake you just installed, it doesn't run `cmake --version`. And I'm having trouble finding where the buildbot clone lives to get https://github.com/staticfloat/julia-buildbot/commit/22eb0736b232d297f71571a03e7ccf6b45cfd89e to take effect

**Comment by staticfloat** [comment]
I did notice that myself, but I seemed to remember something about windows cmake acting very strangely.  The buildbot instance on `ubuntu@build.julialang.org`, in `~/buildbot`.  I've reloaded it.

**Comment by tkelman** [comment]
"very strangely" doesn't usually involve exit status of 127. How did you install it? Adding cygwin gdb might be useful for this.

**Comment by staticfloat** [comment]
I installed it through the cygwin setup, selecting `keep` for everything except `cmake` and `cmake` dependencies.  I'll add `gdb`.

**Comment by tkelman** [comment]
oh, should allow the other stuff like the cygwin dll etc to get upgraded, the cross-compilers should be the only thing you need to hold back

**Comment by staticfloat** [comment]
Looks like it needed a reboot.  `cmake` is much happier now and everything non-mingw is upgraded:

```
$ cmake --version
cmake version 3.6.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by tkelman** [comment]
Ah, maybe the buildbot process or something was keeping some old library loaded. Something is still a bit flaky, jobs are pending for way longer than they should be...

**Comment by tkelman** [comment]
The win32 builder is going to need another shutdown, reboot, and rebaseall of all cygwin processes, buildbot was dying in fork failures. Once that's back up I think we can call this closed.

**Comment by staticfloat** [comment]
Done.
-E

**Comment by tkelman** [comment]
still having trouble? https://build.julialang.org/builders/package_win6.2-x86/builds/1017/steps/Julia%20checkout/logs/stdio

**Comment by staticfloat** [comment]
For future reference, rebasing, enabling ASLR, and removing/recreating the python virtualenv and restarting seems to have done the trick.

**Comment by tkelman** [comment]
You forgot to not upgrade the cross compiler. Need to use cygwin time machine to downgrade back to 4.9

**Comment by staticfloat** [comment]
Shoot, on the very last invocation I must have forgotten to check "keep"
for those packages.  Urgh.

I'm unable to get manual package installation or the time machine to work.
The time machine looks to be down today, not sure what other choices we
have.  My dislike for cygwin increases, despite this problem being my own
fault.
-E

**Comment by tkelman** [comment]
if you still have the downloads locally, it's possible to manually modify the setup.ini listing and use a local copy to act like 4.9.2 is the latest version, from your local files. if you don't have them locally, I can put my copy somewhere along with a setup.ini that I had used.

**Comment by staticfloat** [comment]
Yes, looks like I still have the old files cached locally.  What do I need to do with my `setup.ini` file?

**Comment by tkelman** [comment]
IIRC, change the version numbers and checksums for the mingw packages to match 4.9.2 instead of 5.4

**Comment by tkelman** [comment]
cygwin makes everything a bit of an ordeal, but calling this done now. thanks!

**Comment by tkelman** [comment]
I attempted to run the ansible script on buildslave_centos7.1-x64 (which we missed), but didn't succeed - `ERROR: become is not a legal parameter in an Ansible Playbook`. Could you run that?

**Comment by staticfloat** [comment]
Sure thing.  That error means, (I believe) that your ansible version is too
old.
-E
